services:
  - type: web
    name: study_timer_app
    env: ruby
    buildCommand: ./render-build.sh
    startCommand: bundle exec rails server -b 0.0.0.0
    envVars:
      - key: DATABASE_URL
        value: postgres://study_timer_app_production_user:CJHlCYAU98TWt1LhqsWxCT4SQzOlY9y0@dpg-css626t2ng1s73aghc90-a/study_timer_app_production
