services:
  - type: web
    name: study_timer_app
    env: ruby
    buildCommand: ./render-build.sh
    startCommand: bundle exec rails server -b 0.0.0.0
    envVars:
      - key: DATABASE_URL
        value: postgres://db_study_timer_app_production_user:<zDUkggx0IgHgqY9iZgH47oeG6nlx8yIM>@dpg-cssldgggph6c7396ue70-a:5432/db_study_timer_app_production
    postDeploy: bundle exec rails db:migrate
